language: c
sudo: required
script: ./.travis-run.sh

cache:
  directories:
  - $HOME/.opam
  - /usr/local

env:
  # - OCAML_VERSION=4.00
  # - OCAML_VERSION=4.01
  - OCAML_VERSION=4.02

os:
  - linux
  - osx
